version: 1.0.{build}
clone_depth: 1
build_script:
- ps: >-
    Write-Host "no build required"
test_script:
- ps: >-
    $scriptPath = Join-Path $env:APPVEYOR_BUILD_FOLDER -ChildPath "Test-Docs.ps1"

    & $scriptPath
    
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#build-status'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false