name: EOL Blocker

on:
  pull_request:
    branches: [ master, live ]

jobs:
  check_pull_request_job:
    runs-on: ubuntu-latest
    name: Check files for CRLF
    steps:
    - name: Validate files
      env:
        API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: validate
      uses: microsoftgraph/eol-blocker@v1.0.4
