name: Request TOC generation

on:
  issue_comment:
    types:
    - created

permissions:
  pull-requests: write

jobs:
  request_toc_gen:
    name: Request TOC generation
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '#gen-toc') && github.event.issue.state == 'open' }}
    runs-on: ubuntu-latest
    steps:
    - uses: octokit/request-action@v2.x
      id: get_pull_request
      with:
        route: GET /repos/{owner}/{repo}/pulls/{pull_number}
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        pull_number: ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: Azure/pipelines@v1.x
      with:
        azure-devops-project-url: https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences
        azure-pipeline-name: 'On-demand TOC generation'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        azure-pipeline-variables: '{ "toc_branch" : "${{ fromJson(steps.get_pull_request.outputs.data).head.ref }}" }'
